--KOOPERATIFTEKI TOTAL MEYVE MIKTARINI OGREN---
DROP TABLE MEYVE_TON;
CREATE TABLE MEYVE_TON AS

SELECT URUN_ADI,TOPLAM_MIKTAR_TON FROM
(SELECT URUN_ADI,SUM(MIKTAR_TON) TOPLAM_MIKTAR_TON
FROM URUN
 GROUP BY URUN_ADI
EXCEPT
SELECT URUN_ADI,SUM(MIKTAR_TON) TOPLAM_MIKTAR_TON
FROM URUN
WHERE CINSI='SEBZE'
GROUP BY URUN_ADI) AS MEY;

--KOOPERATIFTEKI TOTAL SEBZE MIKTARINI OGREN---
DROP TABLE SEBZE_TON;
CREATE TABLE SEBZE_TON AS

SELECT URUN_ADI,TOPLAM_MIKTAR_TON FROM
(SELECT URUN_ADI,SUM(MIKTAR_TON) TOPLAM_MIKTAR_TON
FROM URUN
 GROUP BY URUN_ADI
EXCEPT
SELECT URUN_ADI,SUM(MIKTAR_TON) TOPLAM_MIKTAR_TON
FROM URUN
WHERE CINSI='MEYVE'
GROUP BY URUN_ADI) AS MEY;


SELECT*FROM SEBZE_TON