--KOOPERATIFTEKI TOTAL MEYVE MIKTARINI OGREN---

CREATE VIEW MEYVE_TON AS

SELECT URUN_ADI,TOPLAM_MIKTAR_TON FROM
(SELECT URUN_ADI,SUM(MIKTAR_TON) TOPLAM_MIKTAR_TON
FROM URUN
 GROUP BY URUN_ADI
EXCEPT
SELECT URUN_ADI,SUM(MIKTAR_TON) TOPLAM_MIKTAR_TON
FROM URUN
WHERE CINSI='SEBZE'
GROUP BY URUN_ADI) AS MEY;

--KOOPERATIFTEKI TOTAL SEBZE MIKTARINI OGREN---

CREATE VIEW SEBZE_TON AS

SELECT URUN_ADI,TOPLAM_MIKTAR_TON FROM
(SELECT URUN_ADI,SUM(MIKTAR_TON) TOPLAM_MIKTAR_TON
FROM URUN
 GROUP BY URUN_ADI
EXCEPT
SELECT URUN_ADI,SUM(MIKTAR_TON) TOPLAM_MIKTAR_TON
FROM URUN
WHERE CINSI='MEYVE'
GROUP BY URUN_ADI) AS MEY;


SELECT*FROM SEBZE_TON
