--UYELER TABLOSUNA YENI LOGIN-PASSWORD-ENCR----
INSERT INTO UYELER (TC_NO,ADI,SOYADI,CINSIYET,TEL_NO,DOGUM_TARIHI,EMAIL,LOGIN_PASSWORD) VALUES ('1234578901','HASAN','ASLAN','E','905051243123','1990-01-01','ornek@ornek.com',crypt('SIFRE123', gen_salt('bf')));
INSERT INTO UYELER (TC_NO,ADI,SOYADI,CINSIYET,TEL_NO,DOGUM_TARIHI,EMAIL,LOGIN_PASSWORD) VALUES ('9934578901','HASAN','ASLAN','E','905051243123','1990-01-01','ornek2@ornek.com',crypt('SIFRE123', gen_salt('bf')));

SELECT * FROM UYELER WHERE EMAIL LIKE 'ornek@ornek.com' AND LOGIN_PASSWORD= crypt('SIFRE123',LOGIN_PASSWORD);		 

--UYELER UPDATE,TELEFON VE PASSWORD DEĞİŞTİRME EMAIL DEĞİŞTİRME VS---
UPDATE UYELER SET LOGIN_PASSWORD=crypt('999SIFRE', gen_salt('bf')),TEL_NO='9055555555' WHERE TC_NO='1234578901' AND EMAIL='ornek@ornek.com';

--DELETE UYE KAYDI-----
DELETE FROM UYELER WHERE TC_NO='1234578901' AND EMAIL='ornek@ornek.com';

---ARSA BİLGİSİ--EKLEME----

SELECT*FROM ARSA; 

INSERT INTO ARSA (PARSEL,ALAN,KULLANIM_TIPI,TAPU_SAHIBI,TAPU_TARIHI,UYE_ID) VALUES
    ( 5,100,'BIREYSEL','KENDI','1990-01-01',(SELECT UYE_ID from UYELER WHERE EMAIL='ornek@ornek.com' AND TC_NO='1234578901'));
	
---ARSA BILGISI GUNCELLEME----	
UPDATE ARSA SET PARSEL=10 ,ALAN=150 WHERE UYE_ID IN ((SELECT UYE_ID from UYELER WHERE EMAIL='ornek@ornek.com' AND TC_NO='1234578901'));

--ARSA KALDIRMA SİLME-----------

DELETE FROM ARSA WHERE UYE_ID IN ((SELECT UYE_ID from UYELER WHERE EMAIL='ornek@ornek.com' OR TC_NO='1234578901')) AND PARSEL=10 AND ALAN=150 AND TAPU_TARIHI='1990-01-01';


------ADRES EKLEME----
SELECT*FROM ADRES;

INSERT INTO ADRES (IL,ILCE,MAHALLE,ADRES,UYE_ID) VALUES
    ( 'ISTANBUL','BEBEK','ORNEK MAH','ORNEK CAD ORNEK SOK ORNEK APT NO:10',(SELECT UYE_ID from UYELER WHERE EMAIL='ornek2@ornek.com' AND TC_NO='9934578901'));
	
--ADRES GUNCELLEME-------

UPDATE ADRES SET IL='ANKARA' ,ILCE='CANKAYA' WHERE UYE_ID IN ((SELECT UYE_ID from UYELER WHERE EMAIL='ornek@ornek.com' AND TC_NO='1234578901'));

--ADRES SİLME-------

DELETE FROM ADRES WHERE UYE_ID IN ((SELECT UYE_ID from UYELER WHERE EMAIL='ornek@ornek.com' AND TC_NO='1234578901'));

--URUN EKLEME----

INSERT INTO URUN (urun_adi,cinsi,miktar_ton,alis_kg,satis_kg,uret_tarihi,uye_ID) VALUES
    ( 'BUGDAY','SARI',10,5,7,'2020-01-01',(SELECT UYE_ID from UYELER WHERE EMAIL='ornek2@ornek.com' AND TC_NO='9934578901'));

	
SELECT*FROM URUN;


-- URUN GUNCELLEME----

UPDATE URUN SET MIKTAR_TON=800.43,ALIS_KG=0.32,SATIS_KG=2.435 WHERE UYE_ID IN (SELECT UYE_ID from UYELER WHERE EMAIL='ornek2@ornek.com'AND TC_NO='9934578901') AND URUN_ADI='BUGDAY';

----URUN KALDIRMA-----

---EĞER MUŞTERIYE AIT İSE

DELETE FROM URUN WHERE UYE_ID IN (SELECT UYE_ID from UYELER WHERE EMAIL='ornek@ornek.com' AND TC_NO='1234578901') AND URUN_ADI='BUGDAY' AND URET_TARIHI='20200101';
--EĞER SPESIFIK URUN TURU KALDIRILACAKSA
DELETE FROM URUN WHERE URUN_ADI='BUGDAY';




